In [1]:
import numpy as np
a = np.array([1, 2, 3])

In [2]:
a * 3

array([3, 6, 9])

In [3]:
a + 2

array([3, 4, 5])

In [4]:
[1, 2, 3] * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [5]:
b = np.array([2, 2, 0])

In [8]:
a + b

array([3, 4, 3])

In [9]:
a / b

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([0.5, 1. , inf])

In [10]:
a * b

array([2, 4, 0])

In [11]:
np.dot(a, b)

6

In [12]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [14]:
np.linspace(0, 10, 15)

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

In [15]:
c = np.array([[1, 2, 3], [4, 5, 6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
c.shape

(2, 3)

In [20]:
d = np.array([
    [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]],
    [[13, 14, 15], [16, 17, 18], [19, 20, 21], [22, 23, 24]]
    ])
d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [21]:
d.shape

(2, 4, 3)

In [22]:
np.sum(c)

21

In [27]:
np.sum(c, axis=1)

array([ 6, 15])

In [28]:
c.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [29]:
c.reshape(6, 1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [30]:
c.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [32]:
np.transpose(c)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [33]:
# randn返回的是服从标准正态分布的随机值
np.random.randn()

0.16374503418741668

In [34]:
# rand返回0~1的随机数
np.random.rand()

0.26812296289754634

In [35]:
np.random.randn(2, 3)

array([[ 0.37639027,  0.7780145 , -0.47788281],
       [ 1.00509473,  0.07366867, -0.50060239]])

### 索引与切片

In [36]:
a

array([1, 2, 3])

In [37]:
a[0]

1

In [38]:
a[1] = 3

In [39]:
a

array([1, 3, 3])

In [40]:
a[1] = 2

In [41]:
a

array([1, 2, 3])

In [42]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
c[0, 0]

1

In [44]:
d = np.array([0, 5, 2, 7, 1, 9])

In [45]:
d[1:5]

array([5, 2, 7, 1])

In [46]:
d[1:3]

array([5, 2])

In [47]:
# 切片按照[起点:终点]
# [起点:终点:间隔]
d[0:5:2]

array([0, 2, 1])

In [48]:
# 在需要对数组进行翻转时非常方便的用法，建议加强记忆
d[::-1]

array([9, 1, 7, 2, 5, 0])

### 广播

In [49]:
a

array([1, 2, 3])

In [50]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
a + c

array([[2, 4, 6],
       [5, 7, 9]])

In [52]:
a * c

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [66]:
import time

def calculate_time():
    a = np.random.randn(1000000)
    b = [a]
    start_time = time.time()
    for _ in range(1000):
        sum_1 = np.sum(a)
    print("Using Numpy\t %f sec" % (time.time() - start_time))
    start_time = time.time()
    for _ in range(1000):
        sum_2 = sum(b)
    print("Not using Numpy\t %f sec" % (time.time() - start_time))

In [67]:
calculate_time()

Using Numpy	 1.126119 sec
Not using Numpy	 2.949803 sec


In [60]:
a = np.random.randn(10000000)

In [61]:
%timeit np.sum(a)

11.8 ms ± 89.3 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [62]:
%timeit sum(a)

780 ms ± 14.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
